# Generated by Django 3.2 on 2022-02-22 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/signature')),
                ('user', models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('file', models.FileField(upload_to='media/docs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_inbox', models.BooleanField(default=False)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('label', models.ManyToManyField(related_name='labels', to='web_page.Label')),
                ('receiver', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_page.signature')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/profile_contact')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('contact_user', models.ManyToManyField(related_name='contact_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
