# Generated by Django 3.2 on 2022-02-23 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0002_auto_20220224_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/docs'),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='labels', to='web_page.Label'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_page.signature'),
        ),
    ]
