# Generated by Django 3.2 on 2022-02-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mail.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/docs', validators=[mail.validators.validate_file_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('bcc', models.ManyToManyField(related_name='receivers_bcc', to=settings.AUTH_USER_MODEL)),
                ('cc', models.ManyToManyField(related_name='receivers_cc', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(related_name='labels', to='mail.Label')),
                ('receivers', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.signature')),
            ],
        ),
    ]
