# Generated by Django 3.2 on 2022-03-01 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0003_alter_email_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
