# Generated by Django 3.2 on 2022-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20220315_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
