# Generated by Django 3.2 on 2022-03-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_filter_filter_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='title',
        ),
        migrations.AddField(
            model_name='filter',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.label'),
        ),
    ]
