# Generated by Django 3.2 on 2022-04-04 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_alter_label_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
