# Generated by Django 3.2 on 2022-02-23 21:10

import about_user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', about_user.manager.UserManager()),
            ],
        ),
    ]
