# Generated by Django 3.2 on 2022-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='labels', to='mail.Label'),
        ),
    ]
