# Generated by Django 3.2 on 2022-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20220301_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
